### ISSUE TITLE
Merge codes with coreproject

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/MangaAPI#12]
The scraper should be in shinobi

the rest of the logcis should be ported to django-rest-framework

**Comment by tokitou-san** [comment]
> the rest of the logcis should be ported to django-rest-framework

Okay, I get this
> The scraper should be in shinobi

but not this :\
uhh what you mean actually? we gonna make better parser for mangacore
okay I will rewrite this in `django` and `drf`. which gives a better learning curve to me :)

**Comment by baseplate-admin** [comment]
> we gonna make better parser for mangacore

So basically yes. But it's  a bit of a hard work. Can you design mangacore next?

**Comment by tokitou-san** [comment]
> So basically yes. But it's a bit of a hard work. Can you design mangacore next?

Sure, actually I like having mangacore >>> forumcore :P

**Comment by baseplate-admin** [comment]
> Sure, actually I like having mangacore

Thing is i haven't planned the backend architecture for this type. That's why i wanted you to do forum first
