### ISSUE TITLE
refactor: move `__get_parser` to `helpers`

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/MangaAPI#42]
https://github.com/tokitou-san/MangaAPI/blob/e09ad4d36c7001a95c9ece318cb5d3c23bc6fa97/app/api/scrapers/base_manga.py#L13-L15

**Comment by issamansur** [comment]
Hi, again) Do u need to new class, for example, `HTMLHelper`  in new file `helpers/html.py` or move to `helpers/string.py`?

**Comment by issamansur** [comment]
And I can use moved __get_parser() for `most_viewed.py`, `topten.py`, `popular.py` because it use __get_parser().
I think change to:
```
class HTMLHelper:
   @staticmethod
   def __get_parser(url: str) -> HTMLParser: 
       res = requests.get(url) 
       return HTMLParser(res.content) 
```

**Comment by tokitou-san** [comment]
Hi @issamansur :)
> HTMLHelper in new file helpers/html.py

Yes, create a new file `html.py` sounds good -> `HTMLHelper` class ( remove `__` naming convection )
Yup sounds good
```py
class HTMLHelper:
   @staticmethod
   def get_parser(url: str) -> HTMLParser: 
       res = requests.get(url) 
       return HTMLParser(res.content) 
```
