### ISSUE TITLE
refactor: add better `404` response

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/MangaAPI#44]
https://github.com/tokitou-san/MangaAPI/blob/4a0660358d2e40053921458c2588e0f0af82fdfd/app/api/scrapers/base_manga.py#L30

Currently it returns empty fields if manga is not found or any error occurs
Instead I'd like to return a better `404` response with message

**Comment by svlobao** [comment]
Hi tokitou-san, how's it going?

This is literally the first issue I ever tackle, so sorry for any nuisance in advance. 

Here's a checklist of what I am planning to do:

- [ ] Create custom exception class in a new file
- [ ] Raise the custom exception in the "get_manga_id" method, within the BaseMangaScraper class, when the manga is not found
- [ ] Update the "return_on_error" decorator to catch the custom exception and return a 404 response with a message

 I also have a few questions:

1. Do you have in mind other error cases to which you'd like to have more custom exceptions?
2. Are there any other status codes, other than 404, that are yet to be handled?
3. Do you plan to modify the methods that currently return empty values (0, "", [], etc.) to raise custom exceptions as well?

I plan on delivering these tasks within the next 24 to 48h.

**Comment by svlobao** [comment]
Hi tokitou-san! How's it going?

This is going to be the first issue I ever tackle, so I am sorry for any nuisance in advance. 

I would like to ask some questions for some clarification, due to my lack of experience:

1. What is the proper way to help you with this issue? Should I just write some messages in the decorators' response (e.g., lines 30, 36, 42, 51, 57, 83) and handle the empty responses (e.g. lines 65, 71, 77, 91, etc.)?
2. Should I refactor the `return_on_error` decorator to something like:

```
from flask import abort

def return_on_error(default_value):
    def decorator(func):
        def wrapper(self):
            try:
                return func(self)
            except MangaNotFoundError as e:
                # Return a 404 response with a message
                abort(404, str(e))

        return wrapper

    return decorator

```

Where the custom exception `MangaNotFoundError` looks like:

```
class MangaNotFoundError(Exception):
    pass
```

Thanks!

**Comment by tokitou-san** [comment]
Hi @svlobao, sorry for the delayed response.
I've been quite busy with life lately :)

Anyways, so umm I think modifying `return_on_error` decorator is not gonna fly in
Reason:

- Some mangas doesn't has all fields filled, i.e: if a manga has no published date mentioned we return an empty string... see?
- Yea this is the reason why I added this decorator

Instead I think we can check in `endpoints.py` if there is a manga exists, like just check if title is not empty? cause every manga should've at least a title.
```py
async def get_manga(slug: str):
    response = BaseMangaScraper(url=f"https://mangareader.to/{slug}").build_dict()
    
    if not response["title"]:
        raise HTTPException(status_code=404, detail="Manga not found")

    return response
```
Whadya think? btw this is my first FastAPI project :P
I cant code atm, so I would be greatly appreciate it if you could open a PR for this :)
Good day!

**Comment by tokitou-san** [comment]
Hi @svlobao
do you plan to work on this? otherwise I could do this :) lmk

**Comment by svlobao** [comment]
Hi @tokitou-san! Yes, I do plan on working on this. Things has just gotten a little bit busy! Although, it if is an urgent matter for the application, as I am a total junior in this, maybe it would be better off for you to do it yourself. 

If that is not the case, I will surely open a PR for you this week! :)

**Comment by tokitou-san** [comment]
@svlobao Okay sure, then I leave this to you :) waiting for your PR
also take a look https://github.com/tokitou-san/MangaAPI/issues/44#issuecomment-1724748220

**Comment by svlobao** [comment]
@tokitou-san Hi

Just getting in touch to tell you I am planning on opening the PR within the next 24h (to keep you updated that I am still in this with you haha)
